name: Build and Test
on: [push]

jobs:

  frontend:
    name: Build and run frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Print app.js
        run: cat src/frontend/app.js
<<<<<<< HEAD

      - name: node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - run: npm install
      - run: npm test

      - run: cp src/frontend/app.js /dist/app.js
      - run: /dist/app.js
=======
>>>>>>> parent of 8935009... puh
